apiVersion: v1
kind: Service
metadata:
  name: {{ include "ca3s-helm.fullname" . }}
  labels:
    {{- include "ca3s-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.properties.CA3S_TLSACCESS_PORT }}
      targetPort: https
      protocol: TCP
      name: ui-https
  selector:
    {{- include "ca3s-helm.selectorLabels" . | nindent 4 }}
